import { icons } from "./icons.js";

export const shellTemplate = () => `
  <main class="window-shell">
    <aside class="sidebar">
      <div class="sidebar-chrome" data-wails-drag><div class="traffic" data-wails-no-drag><button class="light close" id="closeBtn" aria-label="关闭"></button><button class="light min" id="minBtn" aria-label="最小化"></button><button class="light max" id="maxBtn" aria-label="最大化"></button></div></div>
      <div class="sidebar-identity" data-wails-drag><div class="title"><span class="title-mark">${icons.git}</span> GitRepoMirror</div><div class="env-pill" id="envPill" data-wails-no-drag><i></i><span>正在检查环境</span></div></div>
      <div class="sidebar-navigation"><div class="sidebar-label">工作台</div><button class="nav active" data-view="repositories">${icons.git}<span>镜像仓库</span><b id="repoCount">0</b></button><button class="nav" data-view="logs">${icons.terminal}<span>运行日志</span></button><div class="sidebar-label settings-label">偏好设置</div><button class="nav" data-view="settings">${icons.settings}<span>设置</span></button></div>
      <div class="environment-card" id="environmentCard"></div>
    </aside>
    <div class="main-area"><section class="content"><div id="repositoriesView" class="view"></div><div id="logsView" class="view hidden"></div><div id="settingsView" class="view hidden"></div></section><section class="console collapsed" id="console"><button class="console-head" id="consoleToggle"><span>${icons.terminal} 实时输出</span><span id="consoleStatus">空闲</span><i>⌃</i></button><div class="console-body" id="consoleBody"></div></section></div>
  </main>
  <div class="toast-stack" id="toasts"></div>
  <div class="modal-backdrop hidden" id="modalBackdrop"><form class="modal" id="mirrorForm"><div class="modal-head"><div><h2>创建仓库镜像</h2><p>在代码托管平台之间建立独立镜像。</p></div><button type="button" class="icon-close" id="modalClose">×</button></div><label>源仓库 <span>GitHub 可用 owner/repo，其他平台使用完整 URL</span><input name="source" required placeholder="https://gitlab.com/team/project.git" autocomplete="off"></label><div class="two-col"><label>目标平台<select name="targetPlatform"><option value="github">GitHub</option><option value="gitlab">GitLab</option><option value="generic">其他 Git 平台</option></select></label><label>备份模式<select name="mode"><option value="mirror">完整镜像 · 所有分支与 Tag</option><option value="shallow">浅克隆 · 默认分支最新版本</option></select></label></div><div id="targetFields"></div><div class="two-col"><label>名称前缀<input name="prefix" placeholder="mirror-"></label><label>名称后缀<input name="suffix" placeholder="-backup"></label></div><label class="check-row"><input type="checkbox" name="syncLfs"><span><strong>同步 Git LFS 对象</strong><small>需要本机已安装 Git LFS，可能显著增加耗时和流量</small></span></label><div class="steps" id="modalSteps"><span class="active">1 准备目标库</span><span>2 拉取源代码</span><span>3 推送镜像</span><span>4 清理完成</span></div><div class="modal-actions"><button type="button" class="button secondary" id="modalCancel">取消</button><button type="submit" class="button primary" id="createSubmit">开始备份</button></div></form></div>`;
